import { Stack, Typography } from "@mui/material";
import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import { useContext } from "react";
import Header from "../components/Header";
import { GlobalContext } from "./_app";

const Home: NextPage = () => {
  const { selectedTheme, setSelectedTheme } = useContext(GlobalContext);

  return (
    <Stack alignItems="center" sx={{ bgcolor: "light.main" }}>
      <Stack alignItems="center" sx={{ width: "100%", maxWidth: 1024, px: 8 }}>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <Header />

        <div style={{ width: 300, height: 300, position: "relative" }}>
          <Image
            src={selectedTheme === "dark" ? "/icon_b.png" : "/icon_w.png"}
            alt="Picture of Logo"
            layout="fill"
            objectFit="contain"
          />
        </div>

        <Stack sx={{ bgcolor: "#888888", p: 1, borderRadius: 2, mt: 4 }}>
          <Typography variant="h6">
            Hello, I'm an indie app developer based in South Korea!
          </Typography>
        </Stack>

        <Stack alignItems="flex-start" sx={{ width: "100%", marginTop: 4 }}>
          <Typography variant="body1" fontWeight="bold">
            저는asdfasdfasdfasdfasdfasdf저는asdfasdfasdfasdfa
          </Typography>
        </Stack>
      </Stack>
    </Stack>
  );
};

export default Home;
